name: Build ACAT

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release, Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true   # Enable Git LFS

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
          
    # Build the full application
    - name: Build the Solution
      run: |
        msbuild acat.sln /t:Build /p:Configuration=${{ matrix.configuration }}
      working-directory: src/
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: acat_build
        path: src/Applications/ACATApp/bin/Release
